eval_gemfile('../common_spree_dependencies.rb')

gem 'rails8_spree_core', path: '../core'
gem 'rails8_spree_api', path: '../api'
gem 'rails8_spree_emails', path: '../emails'

group :test, :development do
  gem 'selenium-webdriver'
end

gemspec
