source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.1"
# The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem "propshaft"
# Use sqlite3 as the database for Active Record
gem "sqlite3", ">= 2.1"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# Session manager
gem 'devise', '~> 4.9', '>= 4.9.4'

gem 'rails8_spree', path: '/Users/iltongarcia/Projects/rails/upgrades/rails8_spree'
gem 'rails8_spree_emails', path: '/Users/iltongarcia/Projects/rails/upgrades/rails8_spree/emails'
gem 'rails8_spree_sample', path: '/Users/iltongarcia/Projects/rails/upgrades/rails8_spree/sample'
gem 'rails8_spree_admin', path: '/Users/iltongarcia/Projects/rails/upgrades/rails8_spree/admin'
gem 'rails8_spree_storefront', path: '/Users/iltongarcia/Projects/rails/upgrades/rails8_spree/storefront'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
end
